INSERT INTO Department VALUES ('İnsan Kaynakları');
INSERT INTO Department VALUES ('Muhasebe');
INSERT INTO Department VALUES ('Pazarlama');
INSERT INTO Department VALUES ('Finans');
INSERT INTO Department VALUES ('AR-GE');
INSERT INTO Department VALUES ('Halkla İlişkiler');
INSERT INTO Department VALUES ('Hukuk');
INSERT INTO Department VALUES ('Yönetim');
INSERT INTO Department VALUES ('Üretim');
INSERT INTO Department VALUES ('Enerji');