INSERT INTO Request (RequestType, Explanation, EmployeeSsn) VALUES (1, 'İzin ihtiyacım bulunmaktadır.', 20);
INSERT INTO Request (RequestType, Explanation, EmployeeSsn) VALUES (2, 'Seyahat ihtiyacım bulunmaktadır.', 21);
INSERT INTO Request (RequestType, Explanation, EmployeeSsn) VALUES (3, 'Avans ihtiyacım bulunmaktadır.', 22);
INSERT INTO Request (RequestType, Explanation, EmployeeSsn) VALUES (4, 'Eğitim talebi ihtiyacım bulunmaktadır.', 23);
INSERT INTO Request (RequestType, Explanation, EmployeeSsn) VALUES (5, 'Mesai talebi ihtiyacım bulunmaktadır.', 24);
INSERT INTO Request (RequestType, Explanation, EmployeeSsn) VALUES (1, 'İzin ihtiyacım bulunmaktadır.', 25);
INSERT INTO Request (RequestType, Explanation, EmployeeSsn) VALUES (2, 'Seyahat ihtiyacım bulunmaktadır.', 20);
INSERT INTO Request (RequestType, Explanation, EmployeeSsn) VALUES (3, 'Avans ihtiyacım bulunmaktadır.', 21);
INSERT INTO Request (RequestType, Explanation, EmployeeSsn) VALUES (4, 'Eğitim talebi ihtiyacım bulunmaktadır.', 22);
INSERT INTO Request (RequestType, Explanation, EmployeeSsn) VALUES (5, 'Mesai talebi ihtiyacım bulunmaktadır.', 23);
INSERT INTO Request (RequestType, Explanation, EmployeeSsn) VALUES (1, 'İzin ihtiyacım bulunmaktadır.', 24);
INSERT INTO Request (RequestType, Explanation, EmployeeSsn) VALUES (2, 'Seyahat ihtiyacım bulunmaktadır.', 25);
INSERT INTO Request (RequestType, Explanation, EmployeeSsn) VALUES (3, 'Avans ihtiyacım bulunmaktadır.', 20);
INSERT INTO Request (RequestType, Explanation, EmployeeSsn) VALUES (4, 'Eğitim talebi ihtiyacım bulunmaktadır.', 21);
INSERT INTO Request (RequestType, Explanation, EmployeeSsn) VALUES (5, 'Mesai talebi ihtiyacım bulunmaktadır.', 22);
INSERT INTO Request (RequestType, Explanation, EmployeeSsn) VALUES (1, 'İzin ihtiyacım bulunmaktadır.', 23);
INSERT INTO Request (RequestType, Explanation, EmployeeSsn) VALUES (2, 'Seyahat ihtiyacım bulunmaktadır.', 24);
INSERT INTO Request (RequestType, Explanation, EmployeeSsn) VALUES (3, 'Avans ihtiyacım bulunmaktadır.', 25);
INSERT INTO Request (RequestType, Explanation, EmployeeSsn) VALUES (4, 'Eğitim talebi ihtiyacım bulunmaktadır.', 20);
INSERT INTO Request (RequestType, Explanation, EmployeeSsn) VALUES (5, 'Mesai talebi ihtiyacım bulunmaktadır.', 21);
INSERT INTO Request (RequestType, Explanation, EmployeeSsn) VALUES (1, 'İzin ihtiyacım bulunmaktadır.', 22);
INSERT INTO Request (RequestType, Explanation, EmployeeSsn) VALUES (2, 'Seyahat ihtiyacım bulunmaktadır.', 23);
INSERT INTO Request (RequestType, Explanation, EmployeeSsn) VALUES (3, 'Avans ihtiyacım bulunmaktadır.', 24);
INSERT INTO Request (RequestType, Explanation, EmployeeSsn) VALUES (4, 'Eğitim talebi ihtiyacım bulunmaktadır.', 25);
INSERT INTO Request (RequestType, Explanation, EmployeeSsn) VALUES (5, 'Mesai talebi ihtiyacım bulunmaktadır.', 20);