INSERT INTO AdvanceRequest VALUES (3, 100, NULL);
INSERT INTO AdvanceRequest VALUES (8, 200, NULL);
INSERT INTO AdvanceRequest VALUES (13, 300, NULL);
INSERT INTO AdvanceRequest VALUES (18, 400, NULL);
INSERT INTO AdvanceRequest VALUES (23, 500, NULL);