SELECT * FROM City
SELECT * FROM Company
SELECT * FROM Department
SELECT * FROM Users
SELECT * FROM UserRole
SELECT * FROM Employee
SELECT * FROM Request
SELECT * FROM RequestFlow
SELECT * FROM LeaveRequest
SELECT * FROM TravelRequest
SELECT * FROM AdvanceRequest
SELECT * FROM EducationRequest
SELECT * FROM OverTimeRequest